/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class per_owisho_learn_jni_HelloWorldJNI */

#ifndef _Included_per_owisho_learn_jni_HelloWorldJNI
#define _Included_per_owisho_learn_jni_HelloWorldJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     per_owisho_learn_jni_HelloWorldJNI
 * Method:    sayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_per_owisho_learn_jni_HelloWorldJNI_sayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
